### ISSUE TITLE
Better manager for playing many files

### ISSUE THREAD

**Issue by OlivierVanaschen** [videovillage/Screen-Issues#11]
Hello,

maybe I didn't see how to do it but I'd like to be able to quickly browse through a full directory of files, like when I review a card full of rushes.

Importing files to a playlist and then navigating from one file to another, instead of opening every file in a new window.

Thanks a lot, all the best,

Olivier

**Comment by gregcotten** [comment]
Thanks for this! Playlist support is on this year's roadmap. Coming Soon!

**Comment by gkertai** [comment]
I can see that playlists have been implemented as of v1.2.5. Close this ticket maybe?

**Comment by gregcotten** [comment]
Yes definitely! Playlists are in Screen!
