### ISSUE TITLE
DNxHD 115 MXF crashes Screen

### ISSUE THREAD

**Issue by drasticman** [videovillage/Screen-Issues#12]
Hey guys,

Pretty much the title.  Trying to open a DNxHD 115 MXF file created by MTI Film's Cortex software crashes Screen immediately on my Macbook Pro running macOS 10.14.6.  Crash report attached.
[ScreenCrashReport112519.txt](https://github.com/videovillage/Screen-Issues/files/3887793/ScreenCrashReport112519.txt)

**Comment by gregcotten** [comment]
Hi! Sorry for the problem you are having. We'd love to get this fixed. Any chance you could upload the file to a google drive link we provide? Please email us at support@videovillage.co so we can privately exchange the upload details!

**Comment by drasticman** [comment]
Will do!
