### ISSUE TITLE
10-bit H.264 .mov crashing version 1.1.1 (2031)

### ISSUE THREAD

**Issue by adamwilt** [videovillage/Screen-Issues#13]
10-bit H.264 .mov  files  are crashing version 1.1.1 (2031). They worked previously.

Sample clip: https://www.dropbox.com/s/jqfl0s2xgisadqv/GH5-10bit-H.264.MOV?dl=0

**Comment by gregcotten** [comment]
2 steps forward one step back! Fixed and will be in the next release.

**Comment by adamwilt** [comment]
The thing that irks me about Screen is how slow the developers are to respond and fix bugs. This one took 10 freakin' minutes. Who the heck has time to wait around for 10 whole minutes???  ;-)

**Comment by gregcotten** [comment]
🙌
