### ISSUE TITLE
no pro video formats available

### ISSUE THREAD

**Issue by aaronpicot** [videovillage/Screen-Issues#2]
<img width="510" alt="Screen Shot 2019-10-11 at 1 39 10 PM" src="https://user-images.githubusercontent.com/56454196/66679914-9b50f100-ec2c-11e9-80a9-d410c365faa6.png">

This is the page I get when I try to download pro video formats

**Comment by wilg** [comment]
Looks like Apple's pulled the page for 2.1 but 2.1.1 is available here: https://support.apple.com/kb/DL2020?locale=en_US

**Comment by gregcotten** [comment]
Fixed in the new release! Thanks for bringing this to our attention.
