### ISSUE TITLE
License window disallows ⌘V

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#20]
On the startup screen after a fresh install, pressing CMD+V to paste license information does nothing, but respond with an error beep. It is only possible to paste registered email and license code by using the Paste option in the right-click menu over the text fields.

This is a minor UX annoyance I suppose, but I see no reason to make entering license information more difficult.

**Comment by gregcotten** [comment]
Hi Gabor! I’ll look into this issue, but the easiest way to register is to simply click the green “Register Screen” button. Screen will automatically populate the information for you.

**Comment by gkertai** [comment]
Hi, I am way past the download stage, no longer have that browser window open. I copied the downloaded zip to my editing system and this is the screen I get:

![Screenshot 2020-01-30 at 21 27 52](https://user-images.githubusercontent.com/1874498/73487718-daf04400-43a7-11ea-930a-dec7488b8975.png)

No more green button.

I realize this is not a high priority issue, just wanted to make sure that you are aware of it.

**Comment by gregcotten** [comment]
Understood, but you still need the browser window open to copy/paste your license! Or I guess you could store it in plaintext somewhere.

**Comment by gkertai** [comment]
> You still need the browser window open to copy/paste your license! Or I guess you could store it in plaintext somewhere.

That's what password managers are for.

**Comment by wilg** [comment]
@gkertai The "Register Screen" button is always available on the download page, which can be accessed anytime from the email sent after purchase.

**Comment by gkertai** [comment]
To give you some context: I edit many projects, and for each new project I install a fresh copy of Mac OS and related applications on an external bootable SSD. This helps keep the project consistent and independent of vendor updates even if I have to reopen it after several months/years. Basically I use a single computer booting a different OS/tools setup for each project.

Some of my projects are short-term (e.g. commercials), so I tend to set up a new project drive every month or so. During setup, I need to transfer licenses for my tools to the new system.

I realize now that for the Screen video player it's better to use the license URL (`https://license.videovillage.co/download/…`) than the name/key pair to do these reinstalls. 

I leave this here for reference, maybe it helps other users in a similar situation.
