### ISSUE TITLE
Bug: Alpha channel not isolated properly

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#21]
When I use the *Image* menu *Isolate Channel / Alpha* option or the *Inspector* pop-up *A* radio button to display alpha channel only, it shows a completely white screen, regardless of the underlying alpha content of the video.

RGB view:
![Screen Shot 2020-01-30 at 12 26 51](https://user-images.githubusercontent.com/1874498/73446248-b4f18200-435c-11ea-9406-1d1262ef3809.PNG)

Alpha-only view:
![Screen Shot 2020-01-30 at 12 26 37](https://user-images.githubusercontent.com/1874498/73446261-bae76300-435c-11ea-8f2e-350cd0070730.PNG)

But the same video in FCPX:
![Screen Shot 2020-01-30 at 12 29 15](https://user-images.githubusercontent.com/1874498/73446354-e23e3000-435c-11ea-9a89-2e6929052358.PNG)

Or QuickView:
![Screen Shot 2020-01-30 at 12 25 47](https://user-images.githubusercontent.com/1874498/73446381-ecf8c500-435c-11ea-89d2-feb66ea86c1b.PNG)

This is a ProRes4444 source, in case that matters.

**Comment by gregcotten** [comment]
I really need to find a macOS 10.13 install to check things on, because 10.14+ does not have this issue. In the off-chance, could you send me a one frame QuickTime of this?

**Comment by gkertai** [comment]
Thanks for looking into this! Unfortunately some of my projects are stuck on High Sierra. I tested this on my Mojave 10.14.6 system, and I can easily reproduce it.

Here's a snippet: [TC_02330914_Trimmed.zip](https://github.com/videovillage/Screen-Issues/files/4136159/TC_02330914_Trimmed.zip) (which BTW I trimmed using Screen, it's an awesome feature, and works much easier than QuickTime Player).

**Comment by gregcotten** [comment]
Fixed and will be in the next release!
