### ISSUE TITLE
Indicate field order for interlaced videos

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#22]
The info panel currently does not indicate whether a video is interlaced, and the field order thereof.

This is of a 25i TFF file:
![Screen Shot 2020-02-09 at 1 17 28](https://user-images.githubusercontent.com/1874498/74093982-2c03e480-4ada-11ea-8a0f-de9a1844cc5d.PNG)

Field order is properly indicated for the same file by MediaInfo / ffprobe:
![Screen Shot 2020-02-09 at 1 20 52](https://user-images.githubusercontent.com/1874498/74094004-80a75f80-4ada-11ea-97cd-c934e5850d4c.PNG)

**Comment by gregcotten** [comment]
Done! Will be in the next release.

**Comment by gkertai** [comment]
Wow! That took you like 3 minutes.

**Comment by gregcotten** [comment]
My curiosity was piqued! Just out of curiosity, would you prefer to see 25fps interlaced displayed as "50i"?

**Comment by gkertai** [comment]
As far as I can tell there's no industry consensus over 25i vs 50i (or 30i vs 60i for that matter). Even Apple devs cannot make their minds up: in Final Cut Pro X you have format constants like `FFVideoFormat1440x1080i50` which is displayed as *"1080i HD 1440x1080 25i"* on the interface.

Personally I don't have a strong preference for either, but 25i feels slightly more natural if we call it a "frame rate" (as opposed to a "field rate").

**Comment by gregcotten** [comment]
How about "25fps (50i, Top Field First)" For example

**Comment by gkertai** [comment]
Sounds good!
