### ISSUE TITLE
Crashes on opening very large movies.

### ISSUE THREAD

**Issue by toddfreese** [videovillage/Screen-Issues#24]
I'm using Screen on Catalina on a new MacPro.

When I open any very high resolution movie, Screen crashes.

I'm opening a 26Kx2K ProRes HQ file and it crashes every time.

Here is the crash log:
[Redacted]

**Comment by gregcotten** [comment]
That's a new one! Screen should certainly not crash in this instance, but unfortunately I'm not sure it will be able to play back a file with a dimension greater that 16384 wide or tall. I will need to look into how we can support larger resolutions than that!

**Comment by toddfreese** [comment]
I can provide a sample file on an FTP if you like. They are large 360 degree stitched plates. 

T

**Comment by gregcotten** [comment]
That would be very helpful. Please email us at support@videovillage.co and we'll look into it!

**Comment by ghodgeon** [comment]
Crashes on a tiny file, too.

**Comment by gregcotten** [comment]
> Crashes on a tiny file, too.

**Comment by gregcotten** [comment]
> Crashes on a tiny file, too.

Unrelated - made a new issue for this videovillage/Screen-Issues#25

**Comment by gregcotten** [comment]
We've fixed Screen so it won't crash but simply fail to open videos with a dimension larger than 16384. We'd love to support larger resolution videos, though. @toddfreese if you can contact us at support@videovillage.co we can get a FTP or a Google Drive set up to share a large res video!
