### ISSUE TITLE
Export error after failed trim operation

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#27]
When I use *Export Trimmed…* on a video, sometimes I get a message saying the trim failed (I experienced this on some H.264 files in MP4/MOV containers). No further explanation, and no trace of this in the Console.

So then I try to export the same segment using *Export…* command (with recompression), and I get this: “A movie with this name is currently being exported. Please choose a different file name.”

![Screen Shot 2020-02-28 at 14 34 52](https://user-images.githubusercontent.com/1874498/75626157-43a82780-5bc5-11ea-996b-d53e22a24d66.PNG)

Choosing a different filename does indeed help, but it seems like the failed trim leaves something invisible stuck in the job queue.

**Comment by gregcotten** [comment]
Hmmm... We'll work on better error message for failed exports and trims.

Consider the other issue fixed! Will be in the next update. Thanks!
