### ISSUE TITLE
Discrete GPU switching

### ISSUE THREAD

**Issue by Sweetmate** [videovillage/Screen-Issues#29]
Not sure how much testing you've done with laptops, but on my late 2016 15" Pro  on Catalina 10.15.3, screen does not request a switch from integrated to discrete from the OS and thus has a hard time playing larger, heavier files (and applying LUTs). If I manually switch the system over to discrete graphics using a 3rd party tool called gfxCardStatus and try the same file again, screen plays it without issue and the energy tab in activity monitor shows that Screen is making use of discrete graphics. Even if i specify the discrete gpu as Export Render Device in screen and go to export it won't enable the GPU.

Would you look at making screen request high perf GPU??

**Comment by gregcotten** [comment]
Hi there, Screen should be switching to the high perf GPU on launch... It certainly does on my laptop. I'm not sure what's going on but I'll do some testing and get back to you.

**Comment by Sweetmate** [comment]
rebooted a few times and still happening. with screen 1.1.7 and 1.1.9

**Comment by gregcotten** [comment]
Latest Catalina version, I take it?

**Comment by Sweetmate** [comment]
yup 10.15.3

**Comment by gregcotten** [comment]
OK! Fixed. Update will be out shortly.
