### ISSUE TITLE
Timecode display incorrectly when quickly scrubbing playhead

### ISSUE THREAD

**Issue by julesvm** [videovillage/Screen-Issues#35]
I'm whipping the playhead back and forth around a file and it messes up the TC reading to inconsistent values.

**Comment by gregcotten** [comment]
Hi, what do you mean?

**Comment by gregcotten** [comment]
As a rule, we only let the timecode change when the video frame representing that timecode is displayed.

**Comment by julesvm** [comment]
did a screen capture for you
https://www.dropbox.com/s/8am1gvdua7eaavj/scrubbing.mov?dl=0

**Comment by gregcotten** [comment]
Interesting - the timecode it displays is always accurate to the currently displayed frame - what does Screen say the duration of the clip is? Based on the way it's seeking, seems like it's probably inter frame encoded - H.264 or H.265, right?

Might be easier if you email us at support@videovillage.co and we can set you up with a private video upload link for us to test with.

**Comment by julesvm** [comment]
yeah it's an h264, I have a pores version of same file, and this behaviour isn't present. On prores playhead / TC stays locked.
