### ISSUE TITLE
Default to "Actual Size" for small videos (don't automatically upscale)

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#36]
Currently when I open videos smaller than my display size, Screen tends to upscale them to about ¾ of my display height. This works against my QC attempts, as the scaler blurs the videos, so I need to hit ⌘1/⌘2 every time to get them to display at their actual size.

I was looking through the preference options, but the only relevant-looking item **Remember color and sizing settings** did not affect this behavior at all.

It would be nice to have a preference setting to open videos at their actual size instead of the somewhat unpredictable **Default Size ⌘4**.

**Comment by gregcotten** [comment]
I've been thinking about how to handle this one, actually! Default Size tries to scale the image to be around 70% of your display's area.

I wonder if the best thing would be to have an option to set a maximum window size as a display area percentage, and an optional checkbox for making any videos that are less than whatever that resolution is to scale to their actual (smaller) size?

**Comment by gkertai** [comment]
Yeah, default size is very convenient for most casual viewing use-cases, but not so much for QC. I think the preset 70% is fine.

Most image viewers I come across have a checkbox setting along the lines of *“Do not upscale smaller images”*. Checking this still results in images larger than the display to be scaled down to fit, but if smaller than the display, then they are left at their native size.

**Comment by gregcotten** [comment]
Fixed in 1.2.7!
