### ISSUE TITLE
Small width videos cannot be displayed at their actual size

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#37]
*(Screen v1.2.5)* When I set **Actual Size ⌘1** or **Pixel for Pixel ⌘2** sizing for a video narrower than the amount of space required for the control bar (seems to be ~500px currently), Screen scales down the UI, but then immediately scales the video back up to accommodate the controls. This makes it impossible to display small videos at their actual size.

I think the video could shrink smaller (with black margins) while the UI remains large enough to handle.

---

On a related note, what is the difference between ⌘1 and ⌘2? I thought ⌘2 would give me a squished, pixel-perfect display for non-square pixel videos, but it always does the same as ⌘1.

**Comment by gregcotten** [comment]
Yea, that definitely should be fixed - we do this already when the original resolution is larger than the display - the window scales up as much as possible and the viewer internally scales the rest of the way. As a temp fix, you could put the window in fullscreen mode and then scale pixel for pixel.

"Actual Size" is retina-scale independent - meaning a retina display and a non-retinal display will display the image at the same scale. Preview and Quicktime Player X both have this option.

"Pixel for Pixel" actually takes into account the retina display's actual resolution. If you don't have a Retina display, there will be no difference between Actual Size and Pixel for Pixel.

**Comment by gkertai** [comment]
Thank you for the explanation! Apparently I never tried this on my built-in retina screen, I mostly use external displays for playback. Yet, it's good to know.

**Comment by gregcotten** [comment]
Fixed in 1.2.7!

**Comment by gkertai** [comment]
As of v1.2.12 it still struggles with tall vertical videos. Control panel is only half-visible, like so…

![Screen Shot 2020-10-03 at 13 53 55](https://user-images.githubusercontent.com/1874498/94991018-7f9ed300-0580-11eb-8a12-6341c2a96946.PNG)

This one is 1280×3840 pixels, and Screen would not let me resize the window at all. It reverts to this size whenever I let go of the mouse.

**Comment by gregcotten** [comment]
OK, should be fixed in the next release. Side effect is that you'll get pillarboxed 😥.

**Comment by gkertai** [comment]
Thank you, Greg! Pillarboxing is a small price to pay for all the controls to be visible.

**Comment by gregcotten** [comment]
I wholeheartedly agree!
