### ISSUE TITLE
Cannot ⌘ drag frame screenshots into Path Finder

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#38]
Not sure if this is a bug in Screen or [Path Finder](https://cocoatech.com/) (or the intersection thereof)… When I CMD+drag a frame from Screen to a macOS Finder window, I can drop the screenshot into a folder. When I CMD+drag over a Path Finder window, the drop operation is rejected.

See [screencap video here](https://drive.google.com/file/d/16mDpH90Y2fH5XqSA9AEzOU4hXwW6vuoH/view). *Screen  1.2.6 (2678) on Mojave*

Many other applications (e.g. Skitch, FCPX, Google Chrome) allow dragging and dropping virtual files into Path Finder.

**Comment by jhodges10** [comment]
In my experience, it also didn't work in Slack. Hard to know whether this is an OSX limitation or a Screen one though.

**Comment by gregcotten** [comment]
I think it may be a limitation of the app that is receiving the drag - Screen uses "File Promises" - the image file is written on-demand when the drag is completed. Slack probably doesn't support file promises, and it seems like Path Finder probably doesn't either. For the meantime, you can Edit -> Copy Screenshot and paste into these apps, I believe!

**Comment by jhodges10** [comment]
I realized pretty quick that CMD + SHIFT + C works pretty well to just copy a screenshot and then paste to Slack!
