### ISSUE TITLE
Long H.264 MTS clips take a very long time to load

### ISSUE THREAD

**Issue by adamwilt** [videovillage/Screen-Issues#4]
Long H.264 MTS files take a very long time to load. Clips under 2 minutes load almost immediately; a 6 minute clip takes 5-20 seconds; a 12 minute, 2 GB clip takes 40-50 seconds. All these clips open in under a second using QT Player or VLC.

2 GB sample clip: https://www.dropbox.com/s/p2kekw9noc2hz1r/00061.MTS?dl=0

**Comment by gregcotten** [comment]
Thanks for bringing this to my attention! Your sample clip is invaluable. I've fixed the problem - it will be in the next release!

**Comment by adamwilt** [comment]
Unbelievable: it took me longer to characterize the bug and write it up than it took you to fix it!
