### ISSUE TITLE
(short?) mp4s crashing Screen

### ISSUE THREAD

**Issue by groucho86** [videovillage/Screen-Issues#40]
Hello!

Running Screen 1.2.8 (2701).

I exported 1-second long H.264 MOVs and MP4s out of Mac Resolve 16.2.2 to inspect color metadata.

The MP4s crash Screen upon loading. The MOVs do not. This is probably due to them being so short?
Sample files attached
[mp4_mov_metadata.zip](https://github.com/videovillage/Screen-Issues/files/4805360/mp4_mov_metadata.zip)

**Comment by gregcotten** [comment]
Hi there! I can't reproduce the issue on my end - what version of macOS are you running? Would you mind enabling Screen Preferences -> Usage Data -> Send anonymous crash reports and cause the app to crash?
