### ISSUE TITLE
Improve startup time when opening directly for playback

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#48]
When in Finder I double-click to open a video file with Screen (being the default player), it pops up the _"Welcome to Screen"_ dialog and shows a _"Loading Recent Files…"_ message. This can take up to 10 seconds upon first open after a reboot, or 4-6 seconds upon subsequent opens. Since a particular file was requested for playback, populating the recents panel seems like an unnecessary waste of time, and it makes the player feel slow to load.

**Comment by gregcotten** [comment]
Hi! It's strange that the welcome window would block loading the movie you're trying to load, but I went ahead and made sure that the welcome window doesn't load if the reason Screen opened is due to you opening a movie. Hopefully that will fix it!

**Comment by gkertai** [comment]
Wow, that was quick! I'll make sure to check it as soon as a new release is published. Thank you!

**Comment by gregcotten** [comment]
1.2.12 release is out!
