### ISSUE TITLE
Last frame of video not displayed/recognized

### ISSUE THREAD

**Issue by hotchkiss** [videovillage/Screen-Issues#49]
Using Screen to check a DNxHD LB reference file for color delivery. I exported from Avid with a leader and tail pop. The frame count in Screen's info pop-up is off by one frame, and the last frame with the pop does not play. The file plays back as expected in IINA.

**Comment by gregcotten** [comment]
Hi! Any chance you could email us at support@videovillage.co so we can give you an upload link and take a look at this file? Thanks!

**Comment by gregcotten** [comment]
Fixed and in the next release!

**Comment by gregcotten** [comment]
1.2.12 release is up!
