### ISSUE TITLE
Green and Purple opening DNxHR HQ

### ISSUE THREAD

**Issue by aldenf82** [videovillage/Screen-Issues#52]
My DNxHR HQ exports from Premiere Pro have started only showing in purple and green when viewed in Screen. Older exports don't seem to have any issues. Could be an issue with Premiere, but other players QT, Preview, VLC (as well as web previews on Box, etc.) are opening the files without issue. Screen grabs from my header in an older export and one from this morning:

<img width="1118" alt="Screen Shot 2021-03-07 at 12 54 25 PM" src="https://user-images.githubusercontent.com/80216541/110249488-41994700-7f44-11eb-83be-696897c27efb.png">
<img width="1236" alt="Screen Shot 2021-03-07 at 12 50 48 PM" src="https://user-images.githubusercontent.com/80216541/110249493-46f69180-7f44-11eb-9e4d-ebc10da9410f.png">

Restarting both apps and my machine have no effect. Any help is appreciated. Thanks!

**Comment by gregcotten** [comment]
This looks like a RGB DNx clip being interpreted as YCbCr! What macOS version do you have? If you are on 10.14.5 or higher, can you try updating your Apple pro video formats by clicking (in Screen) Help->Update Pro Video Formats...

**Comment by gregcotten** [comment]
Better yet, just get it directly from Apple's site: https://support.apple.com/kb/DL2050?locale=en_US

**Comment by aldenf82** [comment]
Thanks for the quick reply, Greg! Just installed Pro Video 2.2.1 (Screen said I was up to date but was running 2.2.0) and still no dice - re-exported from Premiere and getting the same issue. Running Mac OS 11.2.2.

**Comment by gregcotten** [comment]
Hmm... can you email us at support@videovillage.co so I can set you up with a private upload link? Need to debug locally.

**Comment by aldenf82** [comment]
Will do. Thanks!

**Comment by gregcotten** [comment]
Fixed and in the new release (1.5.0)!
