### ISSUE TITLE
Show/Hide Export Manager

### ISSUE THREAD

**Issue by robodean** [videovillage/Screen-Issues#54]
It would be great to NOT have the export manager window always open. 
When exporting, the export manager window takes the focus away from the main window, which is really annoying if you are trying to export a series of trimmed clips from the video. Worst yet, once the export has started, even if you switch focus BACK to the main window, the export window steals it back when the export is done. 
So I suppose it is two requests:
- showing the export window should be an option
- if it is open, it should not take focus away from the main window unless user interacts with it. 

Also, I LOVE screens. 

cheers

**Comment by gregcotten** [comment]
Totally agree! I added an option in the preferences to disable automatic focusing of the export manager. Look out for the update in the next few days!

**Comment by gregcotten** [comment]
done!
