### ISSUE TITLE
My copy of Screen is possessed

### ISSUE THREAD

**Issue by adamwilt** [videovillage/Screen-Issues#70]
On Oct 31 2021 this is what I saw:

![image](https://user-images.githubusercontent.com/2841957/139604702-e1a330b2-c1b8-4772-bba8-5446f618dead.png)

I have contacted tech support for an exorcism, but everyone seems to be busy today. With my luck, I won't be able to reproduce the problem tomorrow...   ;-)

**Comment by wilg** [comment]
Scary stuff! (Looks like it uses the old icon though.)

If you'd like to disable this you can do so with this preference:

<img width="339" alt="Screen Shot 2021-10-31 at 4 26 29 PM" src="https://user-images.githubusercontent.com/54353/139604730-236590d2-fdcf-4c64-af7d-2cfb64284796.png">

**Comment by adamwilt** [comment]
:-)

**Comment by gregcotten** [comment]
@adamwilt a ghost in the machine 👻
