### ISSUE TITLE
Preference to permanently hide the Welcome window

### ISSUE THREAD

**Issue by mwjburton** [videovillage/Screen-Issues#71]
I appreciate some people use the Welcome window as a drop target, but for me its something I never use and don't want to keep popping up when I open the app. Could we have a pref to permanently hide it please. Thanks

**Comment by mwjburton** [comment]
Any chance this can go into next release please?

**Comment by mwjburton** [comment]
Yes please, I don't ever need to see that window, so when I open the app or click it in the dock when its already open, I'd like that window disabled if possible. Thanks Greg

**Comment by gregcotten** [comment]
Not showing any interface *on launch* goes against macOS design guidelines (how does the user know the app has launched?), but I suppose I can add that as a preference. I have to say this is the first time I've had such a request.

**Comment by gregcotten** [comment]
(added in latest release)

**Comment by mwjburton** [comment]
Thanks very much, super helpful. Can you update the release notes page - last info is for v1.6.7.
