### ISSUE TITLE
YouTube Pull Error

### ISSUE THREAD

**Issue by MightyJax** [videovillage/Screen-Issues#75]
Won't let me pull anything from YouTube.
Keeps saying Python 3 Error.

**Comment by gregcotten** [comment]
running into some issues here - will try to fix!

**Comment by MightyJax** [comment]
> running into some issues here - will try to fix!

I haven't been able to pull anything for a long while unfortunately.   Please keep me updated .

**Comment by gregcotten** [comment]
This should all be fixed - completely forgot to close this issue!
