### ISSUE TITLE
Input LUT not applied to barcode

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#76]
Not sure if this is a bug or a deliberate omission, but I just realized that the generated barcode is reflecting the original camera colors (LOG), even if an input LUT is selected.

This example is clip `B001C007_180327_R1ZA.mov` from the [ARRI LF Samples page](https://webgate.io/en/directlink/e631dcb5b6ac8eb5) with a LUT embedded into ProRes444XQ:
![Screen Shot 2022-02-25 at 16 50 40](https://user-images.githubusercontent.com/1874498/155745408-f595e650-7c2f-4dde-a2df-012a7ae9176c.png)

The barcode colors remain unchanged whatever LUT I choose for display.

**Comment by gregcotten** [comment]
Will be in the next release!
