### ISSUE TITLE
Time Code incorrect

### ISSUE THREAD

**Issue by mikeammo** [videovillage/Screen-Issues#77]
I create broadcast files with timecode using Avid Media Composer.  Screen does not display correct time-code for QuickTimes or .mxf files.  For instance, an OP1a .mxf file that should have drop-from timecode starting at 00;59;40;00 begins at 00:59:36:12.  The same files are read correctly with other applications. Can this be fixed?

**Comment by gregcotten** [comment]
Can you send an example file to support@videovillage.co with expected start timecodes? Thanks!

**Comment by mikeammo** [comment]
Hi,Here is a link to two test files for a time code issue with Screen.  These files start at DF TC 00;59;50;00 but screen says 00:59:46:12. https://wgbh.cimediacloud.com/r/mDDzC7IXLx63 | Password:  a(tRKEPt7in!Thanks,MikeMichael H. AmundsonNOVASenior Promotions Producer & ***@***.*** Office857.222.8098 Mobile One Guest Street, Boston, MA 02135On Mar 3, 2022, at 4:16 PM, Greg Cotten ***@***.***> ***@***.*** Can you send an example file to ***@***.*** with expected start timecodes? Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by gregcotten** [comment]
Fixed and will be in the next release very soon

**Comment by mikeammo** [comment]
Sounds great, thanks!

**Comment by gregcotten** [comment]
(fixed in latest release)
