### ISSUE TITLE
Canon Cinema Raw Light (.CRM) looks pixelated

### ISSUE THREAD

**Issue by shencgg** [videovillage/Screen-Issues#79]
![A004C054_220401F4_CANON_00190004](https://user-images.githubusercontent.com/90032206/161309226-3c3fadaa-04f9-4dc0-ac8f-cedd6b1dba2a.png)

This is 4K Canon Raw Light .CRM and it shouldn't look like that, please fix :)

Thank you!

**Comment by gregcotten** [comment]
Please set your decode quality!
<img width="309" alt="Screen Shot 2022-04-01 at 10 04 38 AM" src="https://user-images.githubusercontent.com/924470/161309701-eb01da2d-b5a2-4885-a6a6-b57cc4d4bedd.png">
!

**Comment by shencgg** [comment]
> 

Amazing, now it looks fine :)
