### ISSUE TITLE
Garbled image sony mxf from Venice

### ISSUE THREAD

**Issue by JesseDana** [videovillage/Screen-Issues#9]
This how the footage looks in the viewer.

<img width="1440" alt="Sony XMF from Venice" src="https://user-images.githubusercontent.com/57414885/68239170-5b78f180-ffbf-11e9-8728-b97a02fadfd9.png">

Thanks!

**Comment by JesseDana** [comment]
It's recorded xavc qfhd 23.98 480mbs

**Comment by gregcotten** [comment]
Hi Jesse!

We don't support XAVC MXF just yet - I'm surprised it even opened. Any chance you could send me the clip [here](https://drive.google.com/drive/folders/18GtvsbyPltoq1yMRG6mX-4MTRxVhTgkD?usp=sharing)? Please email us at support@videovillage.co if this needs to be a secure upload.

**Comment by JesseDana** [comment]
Well that explains it then haha. Sure I'll email something over.
