### ISSUE TITLE
Canon RAW does not decode at full resolution

### ISSUE THREAD

**Issue by hotchkiss** [videovillage/Screen-Issues#95]
When opening a Canon RAW file, the image has macroblocking as if it is being debayered at a lower resolution. Screenshots of the full resolution frame and screenshot taken through Screen are attached.
![Canon_RAW_Screen](https://user-images.githubusercontent.com/590342/221760363-4f76b057-d496-4e5e-87f4-8d4d78d2b63c.jpg)
![Canon_RAW_FullRes](https://user-images.githubusercontent.com/590342/221760369-5963a5bb-7cef-4ee7-a709-aeb8bee5e455.jpg)

**Comment by gregcotten** [comment]
Did you try setting the debayer quality to Full?

<img width="304" alt="Screenshot 2023-02-27 at 9 16 18 PM" src="https://user-images.githubusercontent.com/924470/221760701-a3ed9d0a-5193-47c3-94ba-18472f312cd9.png">

**Comment by hotchkiss** [comment]
That did it! Of course, my mistake. Thank you!

**Comment by gregcotten** [comment]
No problem!
